---
  - hosts: staging
    environment:
      PYTHONPATH: /home/{{ ansible_user }}/.local/lib/python2.7/site-packages
    tasks:
      - name: Add docker gpg key
        become: true
        apt_key:
          id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present
      - name: Check if docker repository is present
        become: true
        apt_repository:
          repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
          state: present
      - name: Install docker CE
        become: true
        apt:
          name: docker-ce
          state: present
          update_cache: yes
      - name: Install pip
        become: true
        apt:
          name: python-pip
          state: present
          update_cache: yes
      - name: Install docker-py
        pip:
          name: docker
      - name: Install AWS CLI
        pip:
          name: awscli
      - name: Get ECR login credentials and login with Docker
        become: true
        shell: "$(/home/{{ ansible_user }}/.local/bin/aws ecr get-login --no-include-email --region ap-south-1)"
        # shell: "$(/home/ubuntu/.local/bin/aws ecr get-login --no-include-email --region ap-south-1)"
        environment: 
          AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
          AWS_SECRET_ACCESS_KEY : "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
      - name: Create volume for docker
        become: true
        docker_volume:
          name: grammar_logs
      - name: Create volume for IPC named pipes
        become: true
        docker_volume:
          name: ipc_named_pipes
      - name: Run docker
        become: true
        docker_container:
          name: grammar
          image: 453230908534.dkr.ecr.ap-south-1.amazonaws.com/tracified/grammar-staging
          restart: yes
          restart_policy: on-failure
          state: started
          pull: yes
          env:
            QL_PIPE_FIFO_IN: "{{ lookup('env','QL_PIPE_FIFO_IN') }}"
            QL_PIPE_FIFO_OUT: "{{ lookup('env','QL_PIPE_FIFO_OUT') }}"
          volumes:
            - ipc_named_pipes:/tmp
            - grammar_logs:/myapp/logs
      - name: Run docker
        become: true
        docker_container:
          name: grammar-v1
          image: 453230908534.dkr.ecr.ap-south-1.amazonaws.com/tracified/grammar-staging
          restart: yes
          restart_policy: on-failure
          state: started
          pull: yes
          env:
            QL_PIPE_FIFO_IN: "{{ lookup('env','QL_PIPE_FIFO_IN_V1') }}"
            QL_PIPE_FIFO_OUT: "{{ lookup('env','QL_PIPE_FIFO_OUT_V1') }}"
          volumes:
            - ipc_named_pipes:/tmp
            - grammar_logs:/myapp/logs